### ISSUE TITLE
Use path instead of git/registry for -sys dependency

### ISSUE THREAD

**Issue by antoyo** [gtk-rs/webkit2gtk-rs#16]
Hello.
I propose to use `path` instead of `git`/registry in the `Cargo.toml` for the wapper crate to specify the dependency of the `-sys` crate.
This would allow easier testing, removing the need to publish (or change `git` for `path` locally).

What do you think @sdroege @EPashkin @GuillaumeGomez?

**Comment by GuillaumeGomez** [comment]
I don't have a strong opinion about it. It would make local test on `master` branch easier but I don't know if it could result in any unwanted side-effects. If anyone knows more about it? :)

**Comment by sdroege** [comment]
That's basically what I do for gstreamer, in a way. I just have a cargo workspace with all the crates, and they depend on each other via `path="../bla"`. Saved me a lot of time already

**Comment by EPashkin** [comment]
Test on `cairo` shows that using `cairo-sys-rs` by path not causes problem with `.cargo\config\paths`.

**Comment by antoyo** [comment]
We do that, now. Closing.
