### ISSUE TITLE
How to listen `load-finished` signal, get js execution result as string and take jpg/png/etc page snapshot?

### ISSUE THREAD

**Issue by estin** [gtk-rs/webkit2gtk-rs#24]
Hello!

I'm trying to make hobby project with embedding some browser engine and automate it:
 - load page in background
 - submit forms, trigger clicks on some navigation links
 - get results: values and page image
 
I'm do't want use `webdriver` and standalone browsers for that.

`webkit2gtk-rs` is good enough but I can't find any ways to:

1. Determine when document is ready. How to listen `load-finished` signal? 
2. Get result of js execution as string.
3. Get page snapshot.

Where is my research code:
 - loads https://crates.io/
 - wait 3 seconds
 - grab number of downloads by evaluating `parseInt(document.querySelector('.num').innerHTML.split(',').join(''))`
 - exit

```toml
[dependencies]
glib = "0.3.1"
glib-sys = "0.4.0"
webkit2gtk = "0.2.2"
webkit2gtk-sys = "0.4.0"
gtk = "0.2.0"
gobject-sys = "0.4.0" 
```

```rust
extern crate glib;
extern crate gtk;
extern crate webkit2gtk;
extern crate webkit2gtk_sys as ffi;
extern crate glib_sys as glib_ffi;
extern crate gobject_sys as gobject_ffi;

use std::mem::transmute;

use gtk::{ContainerExt, Inhibit, WidgetExt, Window, WindowType, Continue};
use webkit2gtk::{SettingsExt, WebContext, WebView, WebViewExt, WebViewExtManual};

use glib::{IsA};
use glib::signal::connect;

fn main() {
    gtk::init().unwrap();

    let window = Window::new(WindowType::Toplevel);
    let context = WebContext::get_default().unwrap();

    let webview = WebView::new_with_context(&context);
    webview.load_uri("https://crates.io/");
    window.add(&webview);

    let settings = WebViewExt::get_settings(&webview).unwrap();
    settings.set_enable_developer_extras(true);

    // window.show_all();

    // 1. How to connect to `load-finished` signal?
    connect_notify("notify::load-finished", &webview, || {
        println!("notify::load-finished");
    });

    gtk::timeout_add(3000, move || {
        let js = "parseInt(document.querySelector('.num').innerHTML.split(',').join(''))";
        webview.run_javascript_with_callback(js, move |result| {
            match result {
                Ok(result) => {
                    let context = result.get_global_context().unwrap();
                    let value = result.get_value().unwrap();
                    // 2. How to get value as string?
                    println!("Downloads count by `{}`: {:?}", js, value.to_number(&context));
                    // 3. Hot to take png/jpg page snapshot?
                    gtk::main_quit();
                },
                Err(error) => {
                    println!("Some error: {}", error);
                    gtk::main_quit();
                }

            }
        });
        Continue(false)
    });


    window.connect_delete_event(|_, _| {
        gtk::main_quit();
        Inhibit(false)
    });

    gtk::main();
}


fn connect_notify<F: Fn() + 'static, O: IsA<WebView>>(property_name: &str, view: &O, callback: F) {
    let callback: Box<Box<Fn() + 'static>> = Box::new(Box::new(callback));
    let this: *mut ffi::WebKitWebView = view.to_glib_none().0;
    unsafe {
        connect(this as *mut _, &format!("{}", property_name), transmute(notify_trampoline as usize), Box::into_raw(callback) as *mut _);
    }
}


unsafe extern "C" fn notify_trampoline(_gobject: *mut gobject_ffi::GObject, _pspec: *mut gobject_ffi::GParamSpec, user_data: glib_ffi::gpointer) {
    let callback: &Box<Fn() + 'static> = transmute(user_data);
    callback();
} 
```

Sorry about my poor English.

**Comment by antoyo** [comment]
To know when the document is ready, you'll have to create a web extension .
But that's probably overkill.
Maybe you can get something working with `connect_load_changed()` and checking if the load event is `Finished`.

It looks like the API cannot get the value as a string, for now.
It needs to be implemented.

By snapshot, do you mean a screenshot, i.e. an image on the current webpage?
If it is the case, look at this example [here](https://github.com/antoyo/titanium/blob/master/src/webview/mod.rs#L346-L353).

**Comment by estin** [comment]
1. For document ready event would be enough implement something `wait until exists`
```rust

  gtk::timeout_add(N, move || {
        webview.run_javascript_with_callback("document.querySelector('<target element selector>')...", move |result| {
            match result {
                Ok(result) => {
                    // next step
                },
                Err(error) => {
                   // not ready yet
                }

            }
        });
        Continue(true)
    });
```
2. > It looks like the API cannot get the value as a string, for now.

Hm... it's "blocker" for me. May be I can implement it by my self )
Can you give me some pointers?

3. Yes. I need a screenshot of the current page.
You example works for me!

Thank you for you answers, and for the `gtk-rs` and for the `relm` too )

**Comment by antoyo** [comment]
To get a string, you'd need to add the missing binding function in [this file](https://github.com/gtk-rs/javascriptcore-rs/blob/master/javascriptcore-sys/src/lib.rs) and write a safe wrapper in [this one](https://github.com/gtk-rs/javascriptcore-rs/blob/master/src/lib.rs).
Thanks.
