### ISSUE TITLE
Crate Holding Back Adoption of gtk 0.3

### ISSUE THREAD

**Issue by mmstick** [gtk-rs/webkit2gtk-rs#26]
Can't seem to use the crate on **Crates.io** with the recent **gtk** 0.3 release, so am stuck to using 0.2 to compile any projects that use webkit2gtk.

```
error: Multiple packages link to native library `gio`. A native library can be linked only once.

Package `gio-sys v0.5.0`
    ... which is depended on by `gtk-sys v0.5.0`
    ... which is depended on by `gtk-source-sys v0.5.0`
    ... which is depended on by `sourceview v0.3.0`
    ... which is depended on by `cmark-editor v0.1.0 (file:///home/mmstick/Documents/gtkrs-tutorial/demos/chapter_04)`
links to native library `gio`.

Package `gio-sys v0.4.0`
    ... which is depended on by `webkit2gtk-sys v0.4.0`
    ... which is depended on by `webkit2gtk v0.2.2`
    ... which is depended on by `cmark-editor v0.1.0 (file:///home/mmstick/Documents/gtkrs-tutorial/demos/chapter_04)`
```

**Comment by antoyo** [comment]
[This is in the process to be fixed.](https://github.com/gtk-rs/javascriptcore-rs/pulls)
But there's [an issue in a dependency](https://github.com/gtk-rs/soup-sys-rs/pull/8) that prevents me from updating webkit2gtk.
I'll try to fix that as soon as I can.

**Comment by nilgradisnik** [comment]
@antoyo Any progress on this? I'd love to give this a go with the latest 0.3 version. Let me know if I can help with anything.

**Comment by antoyo** [comment]
I will manually fix the code generation as I did last time, to be able to proceed with the crate update:
it should be done by tomorrow.

**Comment by nilgradisnik** [comment]
Thanks! I'll keep my eye on this then.

**Comment by antoyo** [comment]
[It's almost done.](https://github.com/gtk-rs/webkit2gtk-rs/pull/27)
It will probably be done tomorrow.
