### ISSUE TITLE
How to add a native function to the global object?

### ISSUE THREAD

**Issue by quadrupleslap** [gtk-rs/webkit2gtk-rs#29]
Sorry if this is an obvious question, but I can't figure out how to add a function to the global object. https://webkitgtk.org/reference/webkit2gtk/stable/WebKitScriptWorld.html mentions something about a WebKitScriptWorld, but I can't find anything like that in this library.

**Comment by antoyo** [comment]
Sorry, I don't know the answer: this is more of a `webkit2gtk` question.
I can try to add `ScriptWorld` to this binding if needed, though.

**Comment by quadrupleslap** [comment]
Yes, I think this only needs `ScriptWorld` for the event. This is what would ideally happen:

1. Run `webkit_user_content_manager_register_script_message_handler`, which you already have bindings for.
2. Listen to the script world's `window-object-cleared` signal.
3. Somehow make sure that the this event corresponds to my web view?
4. Run `webkit_web_view_run_javascript` to rebind that function to a nicer name than `window.external...`.

Instead of steps 2 (which you don't have bindings for) and 3 (which I wouldn't know how to do anyway), I currently just listen to the `load-changed` event and wait until it reports `load-finished`, which I think is the simplest method (but has an obvious race condition.)

**Comment by quadrupleslap** [comment]
Nevermind, steps 2 and 3 can be replaced with a user script. By the way, this library is really easy to use, so thanks! The documentation isn't available online, though, which is kind of annoying.
