### ISSUE TITLE
not published as a crate?

### ISSUE THREAD

**Issue by jashank** [gtk-rs/webkit2gtk-rs#4]
hello! it would appear this excellent crate isn't on crates.io, and can't readily be discovered. would you mind `cargo publish`ing it and associated crates?

**Comment by antoyo** [comment]
[My idea was to include this crate into the gtk-rs organization.](https://github.com/gtk-rs/gtk/issues/383)
@GuillaumeGomez: What is your opinion on this?
Do I publish it you or do we try to include it like you did with gtksourceview?

**Comment by GuillaumeGomez** [comment]
Depends on what *you* want first. If included in gtk-rs organization, you'll be **forced** (haha) to be a member and the maintainer of this crate.

If this part is ok for you, you'll have to split the sys part out in its own subdir (we won't put it into gtk-rs/sys repository because it's not a "main" crate). And then we will be able to publish.

I hope I forgot nothing. :)

cc @EPashkin @sdroege

**Comment by antoyo** [comment]
I'm okay with that.

**Comment by GuillaumeGomez** [comment]
Great, just waiting from the other members of gtk-rs then. If they agree, you'll have to wait for my return though (around sunday) so we can perform this.

**Comment by sdroege** [comment]
No problem from my side

**Comment by EPashkin** [comment]
https://github.com/gtk-rs/gtk/issues/383#issuecomment-247847699 says that it .girs have [manually fixed quarks](https://github.com/antoyo/webkit2gtk-sys-rs/commit/cbf2d8800275e8af77c2c8b93bd818522fb61c37).
IMHO better find solution without editing gir before transferring.
Other that this no problem from my side as long as other steps in comment above followed

**Comment by EPashkin** [comment]
There also possible problem with docs: currently we generate all docs from single crate (sourceview), not sure that it will be normal when be two separate "root". @GuillaumeGomez, whay you think it?

**Comment by antoyo** [comment]
@EPashkin: I don't remember what is the quarks issue.
We've fixed things in gir and as far as I know, there's no manual edit of the generated Rust code needed for webkit2gtk.

@GuillaumeGomez: If I understand correctly, you want me to move this [repo](https://github.com/antoyo/webkit2gtk-sys-rs) inside [this one](https://github.com/antoyo/webkit2gtk-rs)?
Also, don't forget that there's [this crate](https://github.com/antoyo/webkit2gtk-webextension-rs).

**Comment by GuillaumeGomez** [comment]
@EPashkin: Remember the current doc issue: we need to generate every crate with its last feature so we can have all functions. So with this one, we generate it and copy it directly (not all its folders).

@antoyo: Yes, absolutely. The sys part should be inside this repository if it's not in the gtk-rs/sys repository like cairo and sourceview.

For webextension, as long as it has a gir file (and thus a sys part too), I guess it's fine. Just apply above comments.

**Comment by EPashkin** [comment]
@antoyo, So this crate and sys generated to same code without https://github.com/antoyo/webkit2gtk-sys-rs/commit/cbf2d8800275e8af77c2c8b93bd818522fb61c37 and you just forgot to revert?

**Comment by EPashkin** [comment]
@GuillaumeGomez don't sure that we get working cross-crate links this way.

**Comment by GuillaumeGomez** [comment]
The linking can be done by hand in the worst case so it's not really an issue.

**Comment by antoyo** [comment]
@EPashkin: Oh, that might be it.
I'll try without this manual change.

**Comment by EPashkin** [comment]
@antoyo there also possible problems:
1) webkit2gtk-sys-rs don't have `min_cfg_version="2.4"` in gir-webkit2.toml while `build.rs`  seems build with it,
2) no Soup-2.4.gir, JavaScriptCore-4.0.gir
3) Package webkit2gtk-4.0 not supported for windows.

PS. quarks seems fixed by https://github.com/gtk-rs/gir/pull/275

**Comment by antoyo** [comment]
Quarks are fixed.
I found one problem thought: when generating the sys crate, it uses the name `java_script_core` while my crate is `javascriptcore`.
How can I rename the generated name to `javascriptcore`?

I have both `Soup` and `JavaScriptCore` gir files, but the `JavaScriptCore` one is almost empty (many things missing).

**Comment by sdroege** [comment]
I have the same problem with the name of the GStreamer -sys crates and currently I rename in the generated code. There is no configuration for that in gir (yet) but that might be useful to have. Question is how that would work with other -sys crates depending on yours.

**Comment by EPashkin** [comment]
Yes, there need some config in addition to `external_libraries`, I think about this.

@antoyo, Strange but in current `WebKit2-4.0.gir` has no functions `webkit_javascript_result_get_global_context`, `webkit_javascript_result_get_value` and `webkit_web_view_get_javascript_global_context`

**Comment by antoyo** [comment]
@EPashkin: On ArchLinux, I have these methods, so I believe you have an outdated version of this file.

**Comment by EPashkin** [comment]
I use file from you sys crate

**Comment by thatcodeguy** [comment]
Anyone managed to compile webkit2gtk-rs on Windows?

**Comment by GuillaumeGomez** [comment]
The real question is: did anyone try to compile it on Windows? :p

**Comment by EPashkin** [comment]
I tried but now found windows version, only has package for `webkit`

**Comment by EPashkin** [comment]
* not found

**Comment by thatcodeguy** [comment]
These links might be useful. Will try later.

[https://webkit.org/webkit-on-windows/](https://webkit.org/webkit-on-windows/)
[https://webkit.org/building-webkit-on-windows/](https://webkit.org/building-webkit-on-windows/)

**Comment by EPashkin** [comment]
Note that working all gtk-rs based crates "tested" only on "pc-windows-gnu" toolchains
and this seems will need `pc-windows-mvsc`

**Comment by thatcodeguy** [comment]
[soup-sys-rs](https://github.com/antoyo/soup-sys-rs) links to `gio` inside of `gtk-rs/sys` so I've changed it to use the one published on crates.io.

I've also changed
```
let package_name = "webkit2gtk-4.0";
let shared_libs = ["webkit2gtk-4.0", "javascriptcoregtk-4.0"];
```
to
```
let package_name = "webkitgtk-3.0";
let shared_libs = ["webkitgtk-3.0", "javascriptcoregtk-4.0"];
```

MSYS2/MingW provides that shared library, so I'm testing it.

This is the output I get when running `$ cargo build --example main` inside of `webkit2gtk-rs`:
```
$ cargo build --example main
   Compiling soup-sys v0.3.1 (file:///C:/Users/x/Documents/Code/Rust/webkit_windows/soup-sys-rs)
   Compiling pango v0.1.3
   Compiling cairo-rs v0.1.3
   Compiling gdk-sys v0.3.4
error[E0432]: unresolved import `libc::sockaddr`
  --> C:\Users\x\Documents\Code\Rust\webkit_windows\soup-sys-rs\src\lib.rs:12:5
   |
12 | use libc::sockaddr;
   |     ^^^^^^^^^^^^^^ no `sockaddr` in the root

error: aborting due to previous error

error: Could not compile `soup-sys`.
Build failed, waiting for other jobs to finish...
error: build failed
```

Anyone know why?

Using `stable-x86_64-pc-windows-gnu`.

**Comment by antoyo** [comment]
As you can see [here](https://doc.rust-lang.org/libc), the API of `libc` changes according to the platform.
This type is not in the windows version of it.

**Comment by thatcodeguy** [comment]
From ebfull/pcap/issues/73:

`The winapi crate has a definition for sockaddr, but if i use it my programm using pcap crashes with exit code 0xC0000374 (heap corruption).`

Any other way to work around this issue maybe?

**Comment by thatcodeguy** [comment]
```diff
diff --git a/Cargo.toml b/Cargo.toml
index 8ae5951..a39d1d8 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -13,11 +13,14 @@ pkg-config = "0.3.7"

 [dependencies]
 bitflags = "0.4"
-gio-sys = { git = "https://github.com/gtk-rs/sys" }
-glib-sys = { git = "https://github.com/gtk-rs/sys" }
-gobject-sys = { git = "https://github.com/gtk-rs/sys" }
+gio-sys = "^0.3.3"
+glib-sys = "^0.3.3"
+gobject-sys = "^0.3.3"
 libc = "0.2"

+[target.'cfg(windows)'.dependencies]
+winapi = "0.2.8"
+
 [features]
 v2_24 = []
 v2_26 = ["v2_24"]
diff --git a/src/lib.rs b/src/lib.rs
index e6e546a..b24f32d 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -9,8 +9,13 @@ extern crate glib_sys as glib;
 extern crate gobject_sys as gobject;
 extern crate gio_sys as gio;

+#[cfg(not(windows))]
 use libc::sockaddr;

+#[cfg(windows)]
+extern crate winapi;
+use winapi::ws2def::SOCKADDR as sockaddr;
+
 #[allow(unused_imports)]
 use libc::{c_int, c_char, c_uchar, c_float, c_uint, c_double,
     c_short, c_ushort, c_long, c_ulong,

```

This appears to work, however now we're back to not having the same version of the shared library.
```
   Compiling webkit2gtk v0.1.0 (file:///C:/Users/x/Documents/Code/Rust/webkit_windows/webkit2gtk-rs)
error[E0432]: unresolved import `webkit2gtk::UserContentManager`
  --> examples\main.rs:28:18
   |
28 | use webkit2gtk::{UserContentManager, WebContext, WebView, WebViewExt};
   |                  ^^^^^^^^^^^^^^^^^^ no `UserContentManager` in the root

error: no method named `set_web_extensions_initialization_user_data` found for type `webkit2gtk::WebContext` in the current scope
  --> examples\main.rs:35:13
   |
35 |     context.set_web_extensions_initialization_user_data(&"webkit".to_variant());
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
```

**Comment by thatcodeguy** [comment]
Alexpux/MINGW-packages/issues/1089 might be of interest.

**Comment by antoyo** [comment]
I updated the `webkit2gtk` and `webkit2gtk-webextension` to include their sys crate.

Also, I wonder what to do with the `javascriptcore` and `soup-sys` crates?
Do we include them inside the organization as well?

**Comment by GuillaumeGomez** [comment]
Depends if they're gir crates or not. I don't think it's a good idea to start adding crates that aren't gobject based inside gtk-rs.

**Comment by sdroege** [comment]
libsoup is GObject based, and having a non-sys binding for that would also be very useful... even if hyper is probably a better solution in many cases.

**Comment by antoyo** [comment]
I move the sys crate for the javascript core repository.
Do I need to add the gir files? It is so empty that I didn't use it to generate anything?
I also reorganized the soup-sys repository.

I think we're ready to move the repositories in the gtk-rs organization.

**Comment by GuillaumeGomez** [comment]
Then this is when you want.

**Comment by antoyo** [comment]
The crate is now published, so I'm closing this issue.

**Comment by lukasstevens** [comment]
I have one question if I may. Why was the crate yanked from crates.io?

**Comment by GuillaumeGomez** [comment]
https://crates.io/crates/webkit2gtk isn't.

**Comment by lukasstevens** [comment]
Ah, thank you. Somehow the search only showed the other crate before.

**Comment by zaaack** [comment]
Any updates on windows?
