### ISSUE TITLE
Fix generating webkit2gtk-rs and webkit2gtk-webextension-rs broken by disco gir-files

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/webkit2gtk-rs#48]
cc @GuillaumeGomez, @sdroege, @vhdirk, @antoyo

I will link all related PRs here

**Comment by EPashkin** [comment]
@vhdirk, @antoyo I added partial regens, can you check that your webkit application still works with it?
Meanwhile I will finish generation with latest gir.

**Comment by vhdirk** [comment]
@EPashkin So far I can only conclude that it panics in the exact same place it did before (which is why I created the initial issue in the first place). I think @antoyo has a much more complete application to verify webkit-rs.

**Comment by EPashkin** [comment]
You meant https://github.com/gtk-rs/webkit2gtk-webextension-rs/issues/40 ?
I thought that you solved it somehow, but https://github.com/gtk-rs/webkit2gtk-webextension-rs/pull/41 not merged.
Webkit2gtk not works on Windows, so I can't help with real errors,
even this patches done without actual linking 😢

**Comment by EPashkin** [comment]
Closing
