### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by bauen1** [gtk-rs/webkit2gtk-rs#57]
There is currently no documentation (save for the example) for this crate.

**Comment by antoyo** [comment]
You can use [this](https://docs.rs/webkit2gtk/0.8.0/webkit2gtk/) and [this](https://webkitgtk.org/reference/webkit2gtk/stable/index.html).

**Comment by antoyo** [comment]
It's now hosted [here](https://gtk-rs.org/webkit2gtk-rs/webkit2gtk/).
