### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by jangernert** [gtk-rs/webkit2gtk-rs#63]
I'll open this for visibility. Even with #58 closed there still needs to be a release to use `webkit2gtk-rs` together with the rest of the latest `gtk-rs` stack.

**Comment by antoyo** [comment]
I'm busy these days, so it might take a while before I can do it.
If someone wants that soon, please open a PR to do the regen in the `crate` branch.

**Comment by jangernert** [comment]
I can look into it
Are there docs on how a new release is issued. I don't really understand how `master` and `crate` are related. It seems like they split at some point and were developed separately. What is `master` even used for at that point?

**Comment by antoyo** [comment]
Not sure why it was decided to go this way.
I think master is used to have the git version of every gtk dependencies and of course the latest features, while the crate branch is the branch to be released.

So, to regenerate on the `crate` branch is the same as on master, except you need to update the dependency version in `Cargo.toml` as well.
The documentation for how to regenerate is [here](https://github.com/gtk-rs/gir).
You might need to update the submodules `gir` and `gir-files` to newer version.
