### ISSUE TITLE
UriSchemeRequestExt without finish

### ISSUE THREAD

**Issue by giacomocariello** [gtk-rs/webkit2gtk-rs#67]
Would it be possible to publish a new release of the crate with finish() enabled in UriSchemeRequest trait? It's pretty useless without it and it seems the master branch already contains necessary code.

**Comment by antoyo** [comment]
The [`crate`](https://github.com/gtk-rs/webkit2gtk-rs/blob/crate/src/auto/uri_scheme_request.rs#L25) branch, which is the branch used to publish on crates.io is out-of-date, though.
That would require a regen in order to make it up to date.
Would you want to do it?

**Comment by antoyo** [comment]
Done in version `0.9.1`.
