### ISSUE TITLE
Feature v2_22 doesn't exits on webkit2gtk 0.10

### ISSUE THREAD

**Issue by gigitux** [gtk-rs/webkit2gtk-rs#74]
I need to use the function `set_enable_media_capabilities` which is enabled only by features v2_22, but does not seem to exist

**Comment by antoyo** [comment]
It seems the `Cargo.toml` on the `crate` branch is indeed outdated.
I'll fix this.

**Comment by gigitux** [comment]
@antoyo Doesn't it have to be updated in the cargo branch too? @bilelmoussaoui

**Comment by antoyo** [comment]
It does.

**Comment by gigitux** [comment]
Mmm, I do not think so I do not think so https://github.com/gtk-rs/webkit2gtk-rs/blob/62bb8bf966fc60d4169ea2d873c0b712d270f9f7/Cargo.toml#L29

**Comment by antoyo** [comment]
@gigitux I meant it does in the sense of it has to be updated in that branch too, not that it was updated ;) .

**Comment by antoyo** [comment]
Version 0.11 should fix this.
